project:
  type: website
  output-dir: docs

website:
  title: "jessicamagalit.github.io"
  navbar:
    left:
      - text: Home
        href: index.html
      - text: About
        href: about.html       
      - text: Projects
        href: projects.qmd
      - text: Resume
        href: resume.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
---
<!-- Footer Section -->
<footer>
  <div class="footer-left">
    Left content (e.g., copyright or site info)
  </div>
  <div class="footer-right">
    Right content (e.g., contact info or social media links)
  </div>
</footer>

<style>
  footer {
    display: flex;
    justify-content: space-between;
    padding: 20px;
    background-color: #f8f8f8;
    border-top: 1px solid #ddd;
    position: fixed;
    bottom: 0;
    width: 100%;
  }
  .footer-left {
    text-align: left;
    color: #333;
  }
  .footer-right {
    text-align: right;
    color: #333;
  }
</style>
