project:
  type: website
  output-dir: docs

website:
  title: "jessicamagalit.github.io"
  navbar:
    left:
      - text: Home
        href: index.html
      - text: About
        href: about.html       
      - text: Projects
        href: projects.qmd
      - text: Resume
        href: resume.qmd

page-footer:
  background: light # or 'dark'
  left: "© 2025 Jessica Magalit"
  right: |
    <a href="https://www.linkedin.com/in/jessica-magalit4">LinkedIn</a> |
    <a href="https://github.com/jessicamagalit">GitHub</a> |
    <a href="mailto:jmagalit@colostate.edu">Email</a> |
    <a href="https://www.instagram.com/jm4gs">Instagram</a>
    
format:
   html:
     theme:
       light: minty
       dark: solar
     css: styles.css
     toc: true
     page-layout: full