project:
  type: website
  output-dir: docs

website:
  title: "jessicamagalit.github.io"
  navbar:
    left:
      - text: Home
        href: index.html
      - text: About
        href: about.html       
      - text: Projects
        href: projects.qmd
      - text: Resume
        href: resume.qmd
page-footer:
  left: 2025 Jessica Magalit
  right: