project:
  type: website
  output-dir: docs

website:
  title: "jessicamagalit.github.io"
  navbar:
    left:
      - text: Home
        href: index.html
      - text: About
        href: about.html       
      - text: Projects
        href: projects.qmd
      - text: Resume
        href: resume.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
footer:
  content: |
    <div class="footer-left">
      <p>© 2025 Samantha Csik</p>
    </div>
    <div class="footer-right">
      <a href="https://www.linkedin.com/in/jessica-magalit4/r.com">LinkedIn</a> |
      <a href="https://github.com/jessicamagalit">GitHub</a> |
      <a href="mailto:jmagalit@colostate.edu">Email</a> |
      <a href="https://www.instagram.com/jm4gs">Instagram</a>
    </div>
  position: bottom
---