---
project:
  type: website
  output-dir: docs
---

title: "Jessie Magalit"
image: media/kitties.heic
toc: false
about:
  template: jolla
  image-shape: round
  image-width: 17em
  links:
    - text: LinkedIn
      href: https://www.linkedin.com/in/jessica-magalit4/r.com
    - text: Github
      href: https://github.com/jessicamagalit
---

Hi everyone, my name is Jessie Magalit and I am from Chicago, IL. I am currently double majoring in Ecosystem Science & Sustainability and Apparel Design & Production. Some of my favorite past times include thrifting, sewing, up-cycling, cooking/baking, and going to art museums. I look forward to displaying my academic accomplishments on this website that I created myself using code!

## Education

Colorado State University, Fort Collins | Fort Collins, CO
Bachelors in Ecosystem Science & Sustainability | Aug 2022 - May 2026

## Experience

Computer Lab Operator | Senior Lab Op | January 2023 - present

---
navbar:
  - text: Home
    href: index.html
  - text: Projects
    href: projects.qmd
  - text: Resume
    href: resume.qmd
---
