---
title: "Resume"
---
# Jessica A. Magalit
---

## Education

-Bachelor of Science in Apparel and Merchandising
Expected Graduation May 2026

1st Concentration Apparel Design and Production

-Bachelor of Science in Ecosystem Science and Sustainability				

2nd Concentration Sustainability
Colorado State University, Fort Collins, Colorado					

-Transferred
Completed May 2022
DePaul University, Chicago, Illinois
---

## Skills and Coursework

Skills

-	Photoshop, Illustrator, InDesign, Excel, WordPress, CLO 3D (introductory)
-	Industrial and domestic sewing machines, plotters, scanners, printers, projectors
-	Hand sewing, embroidery, crocheting, upcycling, garment construction and tailoring since 2009

Coursework

-	Apparel Design and Production: Apparel Design I, Apparel and Merchandising Digital Technology, Consumers in the Marketplace, Fashion Illustration, Fashion Industries, Historic Costume, Merchandising Processes, Patternmaking I-III (Flat, draping and CAD), Product Development I, Textile Science I and II

-	Sustainability: Biology I and II, Calculus for Biological Scientists, Ecology, Physics, Physical Geography, Science of Global Climate Change, Systems Theory for Sustainability

-	Business: Accounting I and II, Business Analytics, Business Statistics, Consumer Behavior, Effective Business Communication, Finance, Management, Marketing, Macroeconomics, Microeconomics.
---

## Work Experience

Elliot Consignment | Chicago, IL | April 2022 - June 2022 | Vintage Consignment Sales Associate/Photographer/Editor	

-Authenticated, priced, measured, and inspected the quality of the designer clothes we consign for customers
-Independently styled, photographed, and edited clothes and accessories to be sold online

Target | South Elgin, IL | October 2020 - January 2021 | Fulfillment Expert Team Member

-Completed hundreds of online delivery and pick-up orders during the holiday season and Covid
-Assisted hundreds of customers using product knowledge not only in person, but also online

Zumiez Inc. | West Dundee, IL | November 2018 - August 2019 | Sales Associate/Cashier

-Utilized suggestive selling techniques, product knowledge, and business communication to not only create a welcoming and helpful environment for the customers but also enhance the store’s sales
---

## Industry Experience

AP Design House | Fort Collins, CO | April 2024 - Current
Sewing & Alterations Intern

-	Sewed and produced garments for local brands: Tula and Elizabeth 
-	Specialized in bridal, formalwear, and daywear alterations 
-	Mentored under Anabella Poletti Montgomery and assisted her clients weekly

True Urban Culture Magazine | Remote | October 2021 - January 2022
Fashion & Lifestyle Journalist Intern 

-	Committed 15+ hours per week towards curating and writing and produced 2-3 articles per week
-	Broadened the company’s outreach by sharing a fresh perspective as a member of gen-z and Chicago
---